services:
  postgres:
    image: postgres:15-alpine
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa-network

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - medusa-network

  minio:
    image: minio/minio:latest
    container_name: medusa-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - medusa-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  medusa-network:
    driver: bridge
